import { WorkflowTemplate } from '@/types/workflowTemplates';

export const BUILTIN_WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  // ============================================================================
  // TEMPLATE 1: Keyword Trigger Test
  // ============================================================================
  {
    id: 'tpl_keyword_trigger_test',
    name: 'Keyword Trigger Test',
    description: 'Tests single and multi-keyword detection and instant automated welcome response.',
    category: 'Trigger Testing',
    purpose: 'Test keyword matching.',
    version: '1.0.0',
    triggerType: 'keyword',
    triggerKeyword: 'hello',
    complexity: 'Beginner',
    tags: ['Keyword', 'Trigger', 'Basic', 'Greeting'],
    highlightFeatures: ['Exact & Contains keyword matching', 'Instant text delivery', 'Zero latency test'],
    isOfficial: true,
    nodes: [
      {
        id: 'node_trigger_1',
        type: 'trigger',
        title: 'Keyword: "hello"',
        description: 'Triggers on incoming "hello", "hi", or greeting',
        triggerType: 'keyword',
        triggerKeyword: 'hello',
        config: { text: 'hello' },
        position: { x: 100, y: 200 },
        nextNodeId: 'node_welcome_1',
      },
      {
        id: 'node_welcome_1',
        type: 'message',
        title: 'Send Welcome Message',
        description: 'Instant introductory response',
        messageType: 'text',
        config: {
          text: '👋 Hello! Welcome to our automated WhatsApp system. Your keyword was received successfully!',
        },
        position: { x: 450, y: 200 },
        nextNodeId: 'node_end_1',
      },
      {
        id: 'node_end_1',
        type: 'end',
        title: 'End of Flow',
        description: 'Trigger validation completed',
        config: {},
        position: { x: 800, y: 200 },
      },
    ],
    edges: [
      { id: 'e1_1', source: 'node_trigger_1', target: 'node_welcome_1', animated: true },
      { id: 'e1_2', source: 'node_welcome_1', target: 'node_end_1' },
    ],
  },

  // ============================================================================
  // TEMPLATE 2: Button Routing Test
  // ============================================================================
  {
    id: 'tpl_button_routing_test',
    name: 'Button Routing Test',
    description: 'Validates 3-way interactive quick-reply button dispatch and branch routing logic.',
    category: 'Interactive Buttons',
    purpose: 'Test button click routing.',
    version: '1.0.0',
    triggerType: 'keyword',
    triggerKeyword: 'hello',
    complexity: 'Intermediate',
    tags: ['Buttons', 'Branching', 'Interactive', 'State Machine'],
    highlightFeatures: ['3-Button interactive message', 'Deterministic branch resolution', 'Session pause & resume'],
    isOfficial: true,
    nodes: [
      {
        id: 'node_trigger_2',
        type: 'trigger',
        title: 'Keyword: "hello"',
        description: 'Triggers on greeting keyword',
        triggerType: 'keyword',
        triggerKeyword: 'hello',
        config: { text: 'hello' },
        position: { x: 80, y: 260 },
        nextNodeId: 'node_welcome_2',
      },
      {
        id: 'node_welcome_2',
        type: 'message',
        title: 'Welcome Message',
        description: 'Sends greeting before menu',
        messageType: 'text',
        config: {
          text: 'Welcome! Please choose one of the test options below:',
        },
        position: { x: 380, y: 260 },
        nextNodeId: 'node_buttons_2',
      },
      {
        id: 'node_buttons_2',
        type: 'button',
        title: '3 Option Buttons',
        description: 'Presents Button A, Button B, and Button C',
        messageType: 'interactive_button',
        config: {
          bodyText: 'Select a test path to evaluate engine branch routing:',
          footerText: 'TriPix Automation Engine',
          buttons: [
            { id: 'btn_a', title: 'Option A', type: 'reply' },
            { id: 'btn_b', title: 'Option B', type: 'reply' },
            { id: 'btn_c', title: 'Option C', type: 'reply' },
          ],
        },
        position: { x: 680, y: 260 },
      },
      // Branch A
      {
        id: 'node_msg_a',
        type: 'message',
        title: 'Message A',
        description: 'Dispatched when Option A is selected',
        messageType: 'text',
        config: {
          text: '✅ [Branch A] You selected Option A! Engine routing test succeeded.',
        },
        position: { x: 1040, y: 100 },
        nextNodeId: 'node_end_a',
      },
      {
        id: 'node_end_a',
        type: 'end',
        title: 'End Branch A',
        description: 'Completed Branch A',
        config: {},
        position: { x: 1340, y: 100 },
      },
      // Branch B
      {
        id: 'node_msg_b',
        type: 'message',
        title: 'Message B',
        description: 'Dispatched when Option B is selected',
        messageType: 'text',
        config: {
          text: '✅ [Branch B] You selected Option B! Engine routing test succeeded.',
        },
        position: { x: 1040, y: 260 },
        nextNodeId: 'node_end_b',
      },
      {
        id: 'node_end_b',
        type: 'end',
        title: 'End Branch B',
        description: 'Completed Branch B',
        config: {},
        position: { x: 1340, y: 260 },
      },
      // Branch C
      {
        id: 'node_msg_c',
        type: 'message',
        title: 'Message C',
        description: 'Dispatched when Option C is selected',
        messageType: 'text',
        config: {
          text: '✅ [Branch C] You selected Option C! Engine routing test succeeded.',
        },
        position: { x: 1040, y: 420 },
        nextNodeId: 'node_end_c',
      },
      {
        id: 'node_end_c',
        type: 'end',
        title: 'End Branch C',
        description: 'Completed Branch C',
        config: {},
        position: { x: 1340, y: 420 },
      },
    ],
    edges: [
      { id: 'e2_1', source: 'node_trigger_2', target: 'node_welcome_2', animated: true },
      { id: 'e2_2', source: 'node_welcome_2', target: 'node_buttons_2' },
      { id: 'e2_btn_a', source: 'node_buttons_2', sourceHandle: 'btn_a', target: 'node_msg_a', label: 'Option A' },
      { id: 'e2_end_a', source: 'node_msg_a', target: 'node_end_a' },
      { id: 'e2_btn_b', source: 'node_buttons_2', sourceHandle: 'btn_b', target: 'node_msg_b', label: 'Option B' },
      { id: 'e2_end_b', source: 'node_msg_b', target: 'node_end_b' },
      { id: 'e2_btn_c', source: 'node_buttons_2', sourceHandle: 'btn_c', target: 'node_msg_c', label: 'Option C' },
      { id: 'e2_end_c', source: 'node_msg_c', target: 'node_end_c' },
    ],
  },

  // ============================================================================
  // TEMPLATE 3: Carousel Test
  // ============================================================================
  {
    id: 'tpl_carousel_test',
    name: 'Carousel Test',
    description: 'Tests horizontal multi-card product showcase delivery with rich media and CTA buttons.',
    category: 'E-Commerce & Carousel',
    purpose: 'Test carousel delivery.',
    version: '1.0.0',
    triggerType: 'keyword',
    triggerKeyword: 'hello',
    complexity: 'Intermediate',
    tags: ['Carousel', 'E-Commerce', 'Cards', 'Catalog'],
    highlightFeatures: ['3 Interactive Product Cards', 'Image thumbnails & pricing', 'Fallback list delivery support'],
    isOfficial: true,
    nodes: [
      {
        id: 'node_trigger_3',
        type: 'trigger',
        title: 'Keyword: "hello"',
        description: 'Triggers product showcase flow',
        triggerType: 'keyword',
        triggerKeyword: 'hello',
        config: { text: 'hello' },
        position: { x: 100, y: 220 },
        nextNodeId: 'node_carousel_3',
      },
      {
        id: 'node_carousel_3',
        type: 'carousel',
        title: 'Product Carousel',
        description: 'Displays 3 interactive product showcase cards',
        messageType: 'carousel',
        config: {
          bodyText: '🌟 Discover our top trending products below. Swipe through to view:',
          cards: [
            {
              headerImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
              title: 'Product 1: Velocity Sneakers',
              description: 'Lightweight performance running shoes - $129.00',
              buttons: [{ id: 'buy_prod_1', title: 'Order Product 1' }],
            },
            {
              headerImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
              title: 'Product 2: Titan Smartwatch',
              description: 'Heart rate tracker, AMOLED screen - $249.00',
              buttons: [{ id: 'buy_prod_2', title: 'Order Product 2' }],
            },
            {
              headerImage: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&auto=format&fit=crop&q=80',
              title: 'Product 3: Horizon Shades',
              description: 'Polarized UV400 classic sunglasses - $79.00',
              buttons: [{ id: 'buy_prod_3', title: 'Order Product 3' }],
            },
          ],
        },
        position: { x: 450, y: 220 },
        nextNodeId: 'node_end_3',
      },
      {
        id: 'node_end_3',
        type: 'end',
        title: 'End of Showcase',
        description: 'Carousel delivery verified',
        config: {},
        position: { x: 800, y: 220 },
      },
    ],
    edges: [
      { id: 'e3_1', source: 'node_trigger_3', target: 'node_carousel_3', animated: true },
      { id: 'e3_2', source: 'node_carousel_3', target: 'node_end_3' },
    ],
  },

  // ============================================================================
  // TEMPLATE 4: Wait Node Test
  // ============================================================================
  {
    id: 'tpl_wait_node_test',
    name: 'Wait Node Test',
    description: 'Tests delayed follow-up dispatch, state persistence, and timer scheduling.',
    category: 'Schedulers & Delays',
    purpose: 'Test scheduler and wait nodes.',
    version: '1.0.0',
    triggerType: 'keyword',
    triggerKeyword: 'hello',
    complexity: 'Intermediate',
    tags: ['Delay', 'Scheduler', 'Follow-up', 'Timer'],
    highlightFeatures: ['1-Minute Delay timer', 'Automated state resumption', 'Multi-step trace logging'],
    isOfficial: true,
    nodes: [
      {
        id: 'node_trigger_4',
        type: 'trigger',
        title: 'Keyword: "hello"',
        description: 'Triggers timed follow-up test',
        triggerType: 'keyword',
        triggerKeyword: 'hello',
        config: { text: 'hello' },
        position: { x: 100, y: 200 },
        nextNodeId: 'node_initial_msg_4',
      },
      {
        id: 'node_initial_msg_4',
        type: 'message',
        title: 'Initial Message',
        description: 'First instant touchpoint',
        messageType: 'text',
        config: {
          text: '👋 Hello! We have received your inquiry. Please wait 1 minute while we check your account status...',
        },
        position: { x: 400, y: 200 },
        nextNodeId: 'node_delay_4',
      },
      {
        id: 'node_delay_4',
        type: 'delay',
        title: 'Wait 1 Minute',
        description: 'Pauses workflow execution for 60 seconds',
        config: {
          delayAmount: 1,
          delayUnit: 'minutes',
        },
        position: { x: 720, y: 200 },
        nextNodeId: 'node_followup_msg_4',
      },
      {
        id: 'node_followup_msg_4',
        type: 'message',
        title: 'Follow Up Message',
        description: 'Dispatched after the 1-minute delay expires',
        messageType: 'text',
        config: {
          text: '⏰ [1 Minute Later] Thank you for waiting! Your account is active and verified. How can we help you next?',
        },
        position: { x: 1040, y: 200 },
        nextNodeId: 'node_end_4',
      },
      {
        id: 'node_end_4',
        type: 'end',
        title: 'End of Flow',
        description: 'Delay scheduler test completed',
        config: {},
        position: { x: 1360, y: 200 },
      },
    ],
    edges: [
      { id: 'e4_1', source: 'node_trigger_4', target: 'node_initial_msg_4', animated: true },
      { id: 'e4_2', source: 'node_initial_msg_4', target: 'node_delay_4' },
      { id: 'e4_3', source: 'node_delay_4', target: 'node_followup_msg_4', animated: true },
      { id: 'e4_4', source: 'node_followup_msg_4', target: 'node_end_4' },
    ],
  },

  // ============================================================================
  // TEMPLATE 5: Lead Capture Test
  // ============================================================================
  {
    id: 'tpl_lead_capture_test',
    name: 'Lead Capture Test',
    description: 'Tests conversational variable capture (Name, Email) and CRM lead update pipeline.',
    category: 'Lead Capture & CRM',
    purpose: 'Test variables and CRM actions.',
    version: '1.0.0',
    triggerType: 'keyword',
    triggerKeyword: 'hello',
    complexity: 'Advanced',
    tags: ['Lead Gen', 'CRM', 'Variables', 'Data Capture'],
    highlightFeatures: ['Step-by-step user input capture', 'Dynamic variable interpolation', 'Automatic CRM Deal creation'],
    isOfficial: true,
    nodes: [
      {
        id: 'node_trigger_5',
        type: 'trigger',
        title: 'Keyword: "hello"',
        description: 'Triggers lead onboarding',
        triggerType: 'keyword',
        triggerKeyword: 'hello',
        config: { text: 'hello' },
        position: { x: 80, y: 220 },
        nextNodeId: 'node_ask_name_5',
      },
      {
        id: 'node_ask_name_5',
        type: 'message',
        title: 'Ask Name',
        description: 'Prompts lead for full name',
        messageType: 'text',
        config: {
          text: '👋 Welcome! To get started, what is your full name?',
        },
        position: { x: 380, y: 220 },
        nextNodeId: 'node_save_name_5',
      },
      {
        id: 'node_save_name_5',
        type: 'set_variable',
        title: 'Save Name Variable',
        description: 'Saves input to {{variables.fullName}}',
        config: {
          variableName: 'fullName',
          variableValue: '{{contact.firstName}}',
        },
        position: { x: 680, y: 220 },
        nextNodeId: 'node_ask_email_5',
      },
      {
        id: 'node_ask_email_5',
        type: 'message',
        title: 'Ask Email',
        description: 'Prompts for email address',
        messageType: 'text',
        config: {
          text: 'Great to meet you! What is your best business email address?',
        },
        position: { x: 980, y: 220 },
        nextNodeId: 'node_save_email_5',
      },
      {
        id: 'node_save_email_5',
        type: 'set_variable',
        title: 'Save Email Variable',
        description: 'Saves input to {{variables.email}}',
        config: {
          variableName: 'email',
          variableValue: 'lead@example.com',
        },
        position: { x: 1280, y: 220 },
        nextNodeId: 'node_crm_update_5',
      },
      {
        id: 'node_crm_update_5',
        type: 'crm_action',
        title: 'CRM Lead Update',
        description: 'Creates qualified deal in CRM',
        config: {
          stage: 'qualified',
          leadScore: 85,
          notes: 'Captured via WhatsApp Lead Capture Test Workflow',
        },
        position: { x: 1580, y: 220 },
        nextNodeId: 'node_confirm_msg_5',
      },
      {
        id: 'node_confirm_msg_5',
        type: 'message',
        title: 'Confirmation Message',
        description: 'Sends confirmation to lead',
        messageType: 'text',
        config: {
          text: '🎉 Thank you! Your lead profile has been registered in our CRM. A representative will contact you shortly.',
        },
        position: { x: 1880, y: 220 },
        nextNodeId: 'node_end_5',
      },
      {
        id: 'node_end_5',
        type: 'end',
        title: 'End of Flow',
        description: 'Lead capture workflow completed',
        config: {},
        position: { x: 2180, y: 220 },
      },
    ],
    edges: [
      { id: 'e5_1', source: 'node_trigger_5', target: 'node_ask_name_5', animated: true },
      { id: 'e5_2', source: 'node_ask_name_5', target: 'node_save_name_5' },
      { id: 'e5_3', source: 'node_save_name_5', target: 'node_ask_email_5' },
      { id: 'e5_4', source: 'node_ask_email_5', target: 'node_save_email_5' },
      { id: 'e5_5', source: 'node_save_email_5', target: 'node_crm_update_5' },
      { id: 'e5_6', source: 'node_crm_update_5', target: 'node_confirm_msg_5' },
      { id: 'e5_7', source: 'node_confirm_msg_5', target: 'node_end_5' },
    ],
  },

  // ============================================================================
  // TEMPLATE 6: Complete WhatsApp Demo Flow
  // ============================================================================
  {
    id: 'tpl_complete_whatsapp_demo',
    name: 'Complete WhatsApp Demo Flow',
    description: 'Full multi-branch interactive enterprise flow: Welcome -> 3 Branches (Catalog Carousel, Pricing, CRM Specialist).',
    category: 'Full Demos',
    purpose: 'Full automation engine testing.',
    version: '1.0.0',
    triggerType: 'keyword',
    triggerKeyword: 'hello',
    complexity: 'Advanced',
    tags: ['Enterprise', 'Multi-Branch', 'Full Suite', 'VIP Concierge'],
    highlightFeatures: [
      'Interactive 3-Button branching',
      'Product Carousel & VIP tagging',
      'Instant Pricing matrix',
      'CRM Escalation & Team Notification',
    ],
    isOfficial: true,
    nodes: [
      {
        id: 'node_trigger_6',
        type: 'trigger',
        title: 'Keyword: "hello"',
        description: 'Triggers on incoming "hello" or greeting',
        triggerType: 'keyword',
        triggerKeyword: 'hello',
        config: { text: 'hello' },
        position: { x: 80, y: 300 },
        nextNodeId: 'node_welcome_6',
      },
      {
        id: 'node_welcome_6',
        type: 'message',
        title: 'Welcome Message',
        description: 'Instant personalized greeting',
        messageType: 'text',
        config: {
          text: '🌟 Welcome to our Official WhatsApp Store! How can we assist you today?',
        },
        position: { x: 380, y: 300 },
        nextNodeId: 'node_buttons_6',
      },
      {
        id: 'node_buttons_6',
        type: 'button',
        title: 'Action Button Menu',
        description: 'Presents 3 action paths to customer and pauses',
        messageType: 'interactive_button',
        config: {
          bodyText: 'Please select an option below to get started immediately:',
          footerText: 'Official Verified Account',
          buttons: [
            { id: 'btn_catalog', title: 'Browse Catalog', type: 'reply' },
            { id: 'btn_pricing', title: 'Get Pricing', type: 'reply' },
            { id: 'btn_agent', title: 'Talk To Expert', type: 'reply' },
          ],
        },
        position: { x: 680, y: 300 },
      },
      // Branch 1: Browse Catalog -> Carousel -> Tag Customer -> End
      {
        id: 'node_carousel_6',
        type: 'carousel',
        title: 'Product Carousel',
        description: 'Displays 3 interactive product showcase cards',
        messageType: 'carousel',
        config: {
          bodyText: 'Explore our top trending items below:',
          cards: [
            {
              headerImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
              title: 'Runner Pro Sneakers',
              description: 'Ultra-light breathable performance shoes. $129',
              buttons: [{ id: 'buy_shoes', title: 'Order Shoes' }],
            },
            {
              headerImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
              title: 'Chronos Smart Watch',
              description: 'Titanium chassis, AMOLED sapphire glass. $249',
              buttons: [{ id: 'buy_watch', title: 'Order Watch' }],
            },
            {
              headerImage: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&auto=format&fit=crop&q=80',
              title: 'Aviator Sun Shades',
              description: 'Polarized UV400 classic gold frame. $79',
              buttons: [{ id: 'buy_glasses', title: 'Order Shades' }],
            },
          ],
        },
        position: { x: 1040, y: 120 },
        nextNodeId: 'node_tag_customer_6',
      },
      {
        id: 'node_tag_customer_6',
        type: 'tag_management',
        title: 'Tag Contact: VIP',
        description: 'Adds VIP tag to contact profile',
        actionType: 'tag_contact',
        config: { action: 'add', tag: 'VIP' },
        position: { x: 1360, y: 120 },
        nextNodeId: 'node_end_catalog_6',
      },
      {
        id: 'node_end_catalog_6',
        type: 'end',
        title: 'Catalog Flow Completed',
        description: 'Catalog browsing flow completed',
        config: {},
        position: { x: 1680, y: 120 },
      },
      // Branch 2: Get Pricing -> Pricing Message -> End
      {
        id: 'node_pricing_msg_6',
        type: 'message',
        title: 'Send Pricing Matrix',
        description: 'Dispatches pricing tier details',
        messageType: 'text',
        config: {
          text: '📊 *Exclusive WhatsApp Pricing Plans*:\n\n• *Starter*: $29/mo - 1,000 monthly contacts\n• *Growth*: $79/mo - 10,000 monthly contacts + Workflows\n• *Enterprise VIP*: $199/mo - Unlimited contacts & Dedicated Manager\n\nReply with your plan of interest!',
        },
        position: { x: 1040, y: 320 },
        nextNodeId: 'node_end_pricing_6',
      },
      {
        id: 'node_end_pricing_6',
        type: 'end',
        title: 'Pricing Flow Completed',
        description: 'Pricing information flow completed',
        config: {},
        position: { x: 1360, y: 320 },
      },
      // Branch 3: Talk To Expert -> CRM Action -> Notification -> End
      {
        id: 'node_crm_expert_6',
        type: 'crm_action',
        title: 'Escalate to CRM Specialist',
        description: 'Opens urgent ticket in CRM',
        config: {
          stage: 'negotiation',
          priority: 'urgent',
          notes: 'Customer requested human agent escalation via WhatsApp.',
        },
        position: { x: 1040, y: 520 },
        nextNodeId: 'node_notify_expert_6',
      },
      {
        id: 'node_notify_expert_6',
        type: 'message',
        title: 'Send Expert Confirmation',
        description: 'Confirms live specialist notification',
        messageType: 'text',
        config: {
          text: '👨‍💼 *Live Specialist Alerted*\n\nYour request has been routed to our senior team. An expert will respond directly in this chat shortly.',
        },
        position: { x: 1360, y: 520 },
        nextNodeId: 'node_end_expert_6',
      },
      {
        id: 'node_end_expert_6',
        type: 'end',
        title: 'Escalation Completed',
        description: 'Specialist routing flow completed',
        config: {},
        position: { x: 1680, y: 520 },
      },
    ],
    edges: [
      { id: 'e6_1', source: 'node_trigger_6', target: 'node_welcome_6', animated: true },
      { id: 'e6_2', source: 'node_welcome_6', target: 'node_buttons_6' },
      // Branch 1: Browse Catalog
      { id: 'e6_btn_catalog', source: 'node_buttons_6', sourceHandle: 'btn_catalog', target: 'node_carousel_6', label: 'Browse Catalog' },
      { id: 'e6_car_tag', source: 'node_carousel_6', target: 'node_tag_customer_6' },
      { id: 'e6_tag_end', source: 'node_tag_customer_6', target: 'node_end_catalog_6' },
      // Branch 2: Get Pricing
      { id: 'e6_btn_pricing', source: 'node_buttons_6', sourceHandle: 'btn_pricing', target: 'node_pricing_msg_6', label: 'Get Pricing' },
      { id: 'e6_pricing_end', source: 'node_pricing_msg_6', target: 'node_end_pricing_6' },
      // Branch 3: Talk To Expert
      { id: 'e6_btn_agent', source: 'node_buttons_6', sourceHandle: 'btn_agent', target: 'node_crm_expert_6', label: 'Talk To Expert' },
      { id: 'e6_expert_notify', source: 'node_crm_expert_6', target: 'node_notify_expert_6' },
      { id: 'e6_notify_end', source: 'node_notify_expert_6', target: 'node_end_expert_6' },
    ],
  },
];
