'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Trash2, ShieldAlert, CheckCircle2, Search, ExternalLink } from 'lucide-react';

export default function DataDeletionPage() {
  const [email, setEmail] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<{ url: string; confirmation_code: string } | null>(null);
  const [checkCode, setCheckCode] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email) return;

    setLoading(true);
    try {
      const res = await fetch('/api/meta/data-deletion', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email }),
      });
      const data = await res.json();
      if (res.ok && data.confirmation_code) {
        setResult(data);
      } else {
        alert(data.error || 'Failed to submit data deletion request');
      }
    } catch (err: any) {
      alert(err.message || 'Error submitting request');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#F8FAFC] text-slate-800">
      {/* Top Navbar */}
      <header className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-slate-200/80">
        <div className="max-w-5xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-[#7C3AED] transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>
          <span className="text-xs font-semibold uppercase tracking-wider text-slate-500">
            Meta Compliance & GDPR
          </span>
        </div>
      </header>

      {/* Hero Section */}
      <section className="py-14 bg-white border-b border-slate-200">
        <div className="max-w-4xl mx-auto px-6">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-red-50 text-red-600 border border-red-100 text-xs font-bold uppercase tracking-wider mb-4">
            <Trash2 className="w-3.5 h-3.5" />
            Data Deletion Instructions
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
            User Data Deletion & Privacy Erasure Request
          </h1>
          <p className="mt-3 text-slate-500 text-sm sm:text-base leading-relaxed">
            In compliance with Meta Platform Terms, GDPR Article 17 (Right to Erasure), and CCPA, Passion Fruit provides this dedicated portal to delete your data and track deletion requests.
          </p>
        </div>
      </section>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-6 py-12 space-y-10">
        {/* Step-by-Step Instructions */}
        <section className="bg-white p-8 rounded-2xl border border-slate-200/80 shadow-sm space-y-4">
          <h2 className="text-xl font-bold text-slate-900">How to Delete Your Data via Facebook / Meta</h2>
          <p className="text-sm text-slate-600 leading-relaxed">
            If you signed into Passion Fruit using Facebook Login or authorized Meta WhatsApp Cloud API permissions, you can revoke access and trigger automated data deletion directly through Meta:
          </p>
          <ol className="list-decimal pl-5 text-sm text-slate-700 space-y-2">
            <li>Go to your Facebook profile&apos;s <strong>Settings & Privacy</strong> &gt; <strong>Settings</strong>.</li>
            <li>In the left sidebar, select <strong>Apps and Websites</strong>.</li>
            <li>Locate <strong>Passion Fruit</strong> in the list of authorized applications.</li>
            <li>Click <strong>Remove</strong>. This automatically triggers our real-time Data Deletion Callback endpoint.</li>
            <li>Facebook will provide you with a confirmation code and status tracking link generated by our server.</li>
          </ol>
        </section>

        {/* Self-Service Deletion Form */}
        <section className="bg-white p-8 rounded-2xl border border-slate-200/80 shadow-sm space-y-6">
          <div>
            <h2 className="text-xl font-bold text-slate-900">Instant Self-Service Data Deletion Request</h2>
            <p className="text-sm text-slate-600 mt-1">
              Submit your account email below to permanently purge your profile, WhatsApp messages, contact lists, and Meta API tokens from our database.
            </p>
          </div>

          {result ? (
            <div className="p-6 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-950 space-y-4">
              <div className="flex items-center gap-3">
                <CheckCircle2 className="w-6 h-6 text-emerald-600 shrink-0" />
                <div>
                  <h3 className="font-bold text-emerald-900">Data Deletion Request Processed</h3>
                  <p className="text-xs text-emerald-700 mt-0.5">
                    Your request has been executed and logged. Keep your confirmation code for your records.
                  </p>
                </div>
              </div>

              <div className="bg-white p-4 rounded-xl border border-emerald-200 text-xs font-mono space-y-2">
                <div>
                  <span className="text-slate-500 font-sans font-medium">Confirmation Code: </span>
                  <span className="font-bold text-emerald-700">{result.confirmation_code}</span>
                </div>
                <div>
                  <span className="text-slate-500 font-sans font-medium">Status URL: </span>
                  <Link href={result.url} className="text-[#7C3AED] underline break-all inline-flex items-center gap-1">
                    {result.url} <ExternalLink className="w-3 h-3 inline" />
                  </Link>
                </div>
              </div>

              <Link
                href={result.url}
                className="inline-block px-5 py-2.5 rounded-xl bg-emerald-600 text-white font-semibold text-xs hover:bg-emerald-700 transition-colors shadow-sm"
              >
                View Live Deletion Status & Receipt
              </Link>
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-600 mb-2">
                  Account Email Address
                </label>
                <input
                  type="email"
                  required
                  placeholder="you@company.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="w-full px-4 py-3 rounded-xl border border-slate-300 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 bg-white"
                />
              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full sm:w-auto px-6 py-3 rounded-xl bg-red-600 hover:bg-red-700 text-white font-semibold text-sm transition-colors shadow-sm flex items-center justify-center gap-2 disabled:opacity-50"
              >
                {loading ? 'Processing Deletion...' : 'Permanently Delete My Data'}
              </button>
            </form>
          )}
        </section>

        {/* Existing Confirmation Code Lookup */}
        <section className="bg-white p-8 rounded-2xl border border-slate-200/80 shadow-sm space-y-4">
          <h2 className="text-xl font-bold text-slate-900 flex items-center gap-2">
            <Search className="w-5 h-5 text-slate-400" />
            Track an Existing Deletion Request
          </h2>
          <p className="text-sm text-slate-600">
            Have a confirmation code provided by Meta or our support team? Check its live status here:
          </p>
          <div className="flex flex-col sm:flex-row gap-3">
            <input
              type="text"
              placeholder="pf_del_xxxxxxxx..."
              value={checkCode}
              onChange={(e) => setCheckCode(e.target.value)}
              className="flex-1 px-4 py-3 rounded-xl border border-slate-300 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 bg-white font-mono text-xs"
            />
            <Link
              href={checkCode ? `/data-deletion/status?code=${encodeURIComponent(checkCode)}` : '#'}
              className={`px-6 py-3 rounded-xl bg-slate-900 text-white font-semibold text-sm text-center transition-colors ${
                !checkCode ? 'opacity-50 cursor-not-allowed' : 'hover:bg-slate-800'
              }`}
            >
              Check Status
            </Link>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200 bg-white py-8 text-center text-xs text-slate-500">
        <div className="max-w-4xl mx-auto px-6 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p>&copy; {new Date().getFullYear()} Passion Fruit Inc. All rights reserved.</p>
          <div className="flex gap-4">
            <Link href="/privacy-policy" className="hover:text-slate-900 transition-colors">Privacy Policy</Link>
            <Link href="/terms-of-service" className="hover:text-slate-900 transition-colors">Terms of Service</Link>
            <Link href="/" className="hover:text-slate-900 transition-colors">Home</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
